version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: dep-pipeline-gitlab
    restart: always
    hostname: 'gitlab.local.com'
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['initial_root_password'] = 'P@ssw0rd1234'
        # Add any other gitlab.rb configuration here, each on its own line
    # volumes:
    #   - ./gitlab/config:/etc/gitlab
    #   - ./gitlab/logs:/var/log/gitlab
    #   - ./gitlab/data:/var/opt/gitlab
    networks:
      - dep-pipeline-network

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    depends_on:
      - gitlab
    container_name: dep-pipeline-gitlab-runner
    restart: always
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dep-pipeline-network

  nexus:
    image: sonatype/nexus3:latest
    container_name: dep-pipeline-nexus
    ports:
      - "8081:8081"
      - "5000:5000" # for docker hosted
      - "5001:5001" # for docker proxy
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
    volumes:
      - ./nexus-data:/nexus-data
    networks:
      - dep-pipeline-network

networks:
  dep-pipeline-network:
    driver: bridge