concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test"
  url = "http://gitlab/"
  id = 1
  token = "zzradhgBF58-8xjKQW6p"
  token_obtained_at = 2023-12-01T04:58:27Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"localhost:5000\":{ \"auth\": \"YWRtaW46UEBzc3cwcmQxMjM0\"}}}"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "localhost:5000/my-alpine-curl-image"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
    network_mode = "dep-pipeline_dep-pipeline-network"
